version: "3.9"

services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc -w 2 localhost 2181 | grep -q 'Zookeeper version'"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"   
      - "29092:29092" 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: "true"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sporthub_db}
      MYSQL_USER: ${MYSQL_USER:-sporthub_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-userpass}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Application Services
  eureka-server:
    build: ./eureka-server
    image: ${DOCKER_USERNAME:-local}/sporthub-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8763:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: ./api-gateway
    image: ${DOCKER_USERNAME:-local}/sporthub-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka
    depends_on:
      eureka-server:
        condition: service_healthy

  user-service:
    build: ./user-service
    image: ${DOCKER_USERNAME:-local}/sporthub-user-service:latest
    container_name: user-service
    ports:
      - "9081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-sporthub_db}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER:-sporthub_user}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-userpass}
      - SPRING_REDIS_HOST=redis
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  court-service:
    build: ./court-service
    image: ${DOCKER_USERNAME:-local}/sporthub-court-service:latest
    container_name: court-service
    ports:
      - "9082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-sporthub_db}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER:-sporthub_user}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-userpass}
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  rezervation-service:
    build: ./rezervation-service
    image: ${DOCKER_USERNAME:-local}/sporthub-rezervation-service:latest
    container_name: rezervation-service
    ports:
      - "9083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-sporthub_db}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER:-sporthub_user}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-userpass}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    image: ${DOCKER_USERNAME:-local}/sporthub-payment-service:latest
    container_name: payment-service
    ports:
      - "9084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-sporthub_db}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER:-sporthub_user}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-userpass}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    image: ${DOCKER_USERNAME:-local}/sporthub-notification-service:latest
    container_name: notification-service
    ports:
      - "9085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  default:
    name: sporthub-net
